# Generated by Django 4.1.3 on 2024-11-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='power_usage',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
