# Generated by Django 5.1.3 on 2024-11-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_appliance_power_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
